In [6]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("olistbr/brazilian-ecommerce")

print("Path to dataset files:", path)

Downloading to C:\Users\Karandeep Singh\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\2.archive...

100%|█████████████████████████████████████████████████████████████████████████████| 42.6M/42.6M [00:13<00:00, 3.39MB/s]

Extracting files...

Path to dataset files: C:\Users\Karandeep Singh\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2

In [1]:
import pandas as pd 

url = r"C:\Users\Karandeep Singh\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2\olist_customers_dataset.csv"

customers = pd.read_csv(url)

In [2]:
customers.shape

(99441, 5)

In [3]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [4]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  str
 1   customer_unique_id        99441 non-null  str
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  str
 4   customer_state            99441 non-null  str
dtypes: int64(1), str(4)
memory usage: 3.8 MB

In [5]:
customers.isnull().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [6]:
customer_summary = pd.DataFrame({
    "Data Type" : customers.dtypes,
    "Null Value" : customers.isnull().sum()
})

print(customer_summary)

                         Data Type  Null Value
customer_id                    str           0
customer_unique_id             str           0
customer_zip_code_prefix     int64           0
customer_city                  str           0
customer_state                 str           0

In [7]:
customers.columns

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

In [8]:
customers.duplicated().sum()

np.int64(0)

In [9]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [10]:
customers["customer_unique_id"].duplicated().sum()

np.int64(3345)

In [11]:
customers[customers["customer_unique_id"].duplicated(keep=False)].sort_values("customer_unique_id").head(20)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
35608,24b0e2bd287e47d54d193e7bbb51103f,00172711b30d52eea8b313a7f2cced02,45200,jequie,BA
19299,1afe8a9c67eec3516c09a8bdcc539090,00172711b30d52eea8b313a7f2cced02,45200,jequie,BA
20023,1b4a75b3478138e99902678254b260f4,004288347e5e88a27ded2bb23747066c,26220,nova iguacu,RJ
22066,f6efe5d5c7b85e12355f9d5c3db46da2,004288347e5e88a27ded2bb23747066c,26220,nova iguacu,RJ
72451,49cf243e0d353cd418ca77868e24a670,004b45ec5c64187465168251cd1c9c2f,57055,maceio,AL
87012,d95f60d70d9ea9a7fe37c53c931940bb,004b45ec5c64187465168251cd1c9c2f,57035,maceio,AL
36269,8ac44e9c15d396b8c3c7cbab0fff4536,0058f300f57d7b93c477a131a59b36c3,41370,salvador,BA
61403,f530197ea86ced9488a03d055e118ebf,0058f300f57d7b93c477a131a59b36c3,40731,salvador,BA
87414,cbb68c721ba9ddb30d8a490cc1897fa1,00a39521eb40f7012db50455bf083460,72595,brasilia,DF
54881,876356df457f952458a764348e1858bc,00a39521eb40f7012db50455bf083460,72595,brasilia,DF
672,102fc0966044243157bb81e4ee0a251e,00cc12a6d8b578b8ebd21ea4e2ae8b27,3178,sao paulo,SP
8960,c0a44bf37d5601228051fc07852f951f,00cc12a6d8b578b8ebd21ea4e2ae8b27,3178,sao paulo,SP
4034,71c7265705afd84d030d6adc3122d8dd,011575986092c30523ecb71ff10cb473,30660,belo horizonte,MG
58583,bc4011fd2a5106761b5ba943c8fbd1b2,011575986092c30523ecb71ff10cb473,30660,belo horizonte,MG
90152,3db635076c27c1d6a8618bc5a6e70ad2,011b4adcd54683b480c4d841250a987f,44200,santo amaro,BA
96494,7e16c78f08de9b2ec5b9eff657934019,011b4adcd54683b480c4d841250a987f,44200,santo amaro,BA
54038,e024c1515b1062b1e7e613f840c35ba3,012452d40dafae4df401bced74cdb490,3984,sao paulo,SP
45307,f8e05a045de09e7855c9df3bb8815e0e,012452d40dafae4df401bced74cdb490,3220,sao paulo,SP
52526,c276d4ce04e35d109575d3282cd2bd20,012a218df8995d3ec3bb221828360c86,6550,pirapora do bom jesus,SP
12966,e4bee874d6368c127e7ca2a6fd7545ff,012a218df8995d3ec3bb221828360c86,6550,pirapora do bom jesus,SP

In [12]:
customers[customers["customer_unique_id"].duplicated(keep=False)] \
    .sort_values("customer_unique_id") \
    .head(20)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
35608,24b0e2bd287e47d54d193e7bbb51103f,00172711b30d52eea8b313a7f2cced02,45200,jequie,BA
19299,1afe8a9c67eec3516c09a8bdcc539090,00172711b30d52eea8b313a7f2cced02,45200,jequie,BA
20023,1b4a75b3478138e99902678254b260f4,004288347e5e88a27ded2bb23747066c,26220,nova iguacu,RJ
22066,f6efe5d5c7b85e12355f9d5c3db46da2,004288347e5e88a27ded2bb23747066c,26220,nova iguacu,RJ
72451,49cf243e0d353cd418ca77868e24a670,004b45ec5c64187465168251cd1c9c2f,57055,maceio,AL
87012,d95f60d70d9ea9a7fe37c53c931940bb,004b45ec5c64187465168251cd1c9c2f,57035,maceio,AL
36269,8ac44e9c15d396b8c3c7cbab0fff4536,0058f300f57d7b93c477a131a59b36c3,41370,salvador,BA
61403,f530197ea86ced9488a03d055e118ebf,0058f300f57d7b93c477a131a59b36c3,40731,salvador,BA
87414,cbb68c721ba9ddb30d8a490cc1897fa1,00a39521eb40f7012db50455bf083460,72595,brasilia,DF
54881,876356df457f952458a764348e1858bc,00a39521eb40f7012db50455bf083460,72595,brasilia,DF
672,102fc0966044243157bb81e4ee0a251e,00cc12a6d8b578b8ebd21ea4e2ae8b27,3178,sao paulo,SP
8960,c0a44bf37d5601228051fc07852f951f,00cc12a6d8b578b8ebd21ea4e2ae8b27,3178,sao paulo,SP
4034,71c7265705afd84d030d6adc3122d8dd,011575986092c30523ecb71ff10cb473,30660,belo horizonte,MG
58583,bc4011fd2a5106761b5ba943c8fbd1b2,011575986092c30523ecb71ff10cb473,30660,belo horizonte,MG
90152,3db635076c27c1d6a8618bc5a6e70ad2,011b4adcd54683b480c4d841250a987f,44200,santo amaro,BA
96494,7e16c78f08de9b2ec5b9eff657934019,011b4adcd54683b480c4d841250a987f,44200,santo amaro,BA
54038,e024c1515b1062b1e7e613f840c35ba3,012452d40dafae4df401bced74cdb490,3984,sao paulo,SP
45307,f8e05a045de09e7855c9df3bb8815e0e,012452d40dafae4df401bced74cdb490,3220,sao paulo,SP
52526,c276d4ce04e35d109575d3282cd2bd20,012a218df8995d3ec3bb221828360c86,6550,pirapora do bom jesus,SP
12966,e4bee874d6368c127e7ca2a6fd7545ff,012a218df8995d3ec3bb221828360c86,6550,pirapora do bom jesus,SP

In [13]:
customers["customer_city"].nunique()

4119

In [14]:
customers["customer_state"].nunique()

27

In [15]:
customers["customer_state"].unique()

<StringArray>
['SP', 'SC', 'MG', 'PR', 'RJ', 'RS', 'PA', 'GO', 'ES', 'BA', 'MA', 'MS', 'CE',
 'DF', 'RN', 'PE', 'MT', 'AM', 'AP', 'AL', 'RO', 'PB', 'TO', 'PI', 'AC', 'SE',
 'RR']
Length: 27, dtype: str

In [16]:
customers.sample(30)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
15610,5738d0a3932e3ae32a2169b9040e5c0b,35a1e3dc12ca1b9f2fca417827fd6183,86600,rolandia,PR
81394,0ebc6c73d89878fb3a1d039df4f3c8a1,06485620b716c476c2faf915f662674e,13084,campinas,SP
19648,6f0b329047469b27994d99813dad1432,6482034a22aaf6fbd2a2d23424debe3d,36790,mirai,MG
17217,7e37c4691de2262c9faaa4096d2d8c5a,e9975df17eaae863301b6c1053370725,72318,brasilia,DF
36233,f216989f29fffd9bdbb0debc76afe3f7,df6e946d46fc243a9818553b35fdac9c,12922,braganca paulista,SP
54578,dbb71dc9efb3e86f11b03e57afea00b8,45003601a32438990718ab4c20ad369b,57420,batalha,AL
43174,7d42d764ec16aebab2afd3d9802e40d7,6689e9f9ce799fb048f33674671a6390,72110,brasilia,DF
14004,a7bd7bcfe3fa72f1c1a3565f7dde6ca2,b1a15c9e2d508753b52cf3d6eae74808,37815,santa cruz do prata,MG
40014,591ff4992a8a79c6dd2e72a202c728ff,2381f8e91d5722b85b133e5b2a27dd54,33170,santa luzia,MG
94965,398999978297b981626b0f4524a66dfe,b6b375c8ce95327a2566a1dc4c72d665,20740,rio de janeiro,RJ
70817,b1569d3f7a5e660a197baf45e5c649cb,35ac6d958fd9d525bd2fceb38f85a35d,12922,braganca paulista,SP
26264,0f3e1ba8c59cc73f5957cc74d9e25698,6e461ec96c9aad81128aca921cfe901d,9271,santo andre,SP
75083,4e2b70d245c3a00cc4bf8ef95d9dbadb,0b355a14c548a718b4e423a3914bdc17,63630,pedra branca,CE
78193,b6debdaf65d20e037db74e2d1c66e22b,106abb15071cec3557f8cd3b89384e99,32146,contagem,MG
72924,af5e377c92351996f031b00fd38a4958,c692007cb765407ea7510cb5b4f47512,9260,santo andre,SP
97687,555775a9601baea5bd2e64b3a403d483,34b2f3c3cb07567280fa300dc3bbb4c3,35700,sete lagoas,MG
42468,05fdac815ea6a7f430e1dde5c80bd6c4,5b2bd431d04a7e547aa07ffedf4b738a,85851,foz do iguacu,PR
36485,a3c9f9938f51f409773bbda6b13f7f3b,4162c8f38b17df48915250f4fcd3a080,71660,brasilia,DF
60550,ccbe7fd54aa82159f48ade29b2bd4b06,679d04027a902ad4c19da1382962a420,89812,chapeco,SC
19391,c2e77a3d32b706cd18bd8e3b464999b3,592d5d086e0de4ea2530499b9e40bb38,75690,caldas novas,GO
74872,5bc60d44810934427ba9965878717888,3e3f84de0e6b6590c0a535d34281a222,2410,sao paulo,SP
78563,65ea0275064d8137b41e097076e70415,7fbecaab8a33b21ca0bb6ee1f4d26658,41810,salvador,BA
21753,7bd7c83d0826aca36fe5e3dc45fd9276,5fb203a0b6157948f715f04737dd20ad,18606,botucatu,SP
15480,e5631483f7f9e6c09cfa0a7359e3f087,79d50677053d3b71d9460f6c0a5555d7,89460,canoinhas,SC
44301,ffe6d825d8a60d5cca942bcc57e9d8e6,03219f704113c9e40797774e4ddb532d,52190,recife,PE
63358,6b191a8aa869ef67263bddff1e7722ce,d4012b60353a88a25a866f83e5201686,78320,juina,MT
5967,a1d87ae5a106ad3b35345b50f226cc8c,47df3391ba10bd28c75e2e0bc53b5dfd,35420,mariana,MG
87223,fdf2fde76977db18487346f9febd301a,5b59166412dd5595f77a43b217c39132,3067,sao paulo,SP
95228,3ce2aed29f86a6e0051d5dbe89c0306c,a7efaafa37906b32b972672b8f844271,9541,sao caetano do sul,SP
30660,a83d9778528a50b4850c15eddb39ab57,b174f842ed0fe72ba49abed080d8d15e,52061,recife,PE

In [17]:
customers['customer_zip_code_prefix'].unique()

array([14409,  9790,  1151, ...,  5538, 74980, 99043], shape=(14994,))

In [18]:
customers['customer_zip_code_prefix'].sample(20)

35959    13874
18413    13905
27102    31360
98363    18890
69701     1548
85023    63430
75086     4763
51859    48900
52618    28907
36967    28800
43946    33400
77069    94010
17148     4134
26813     9910
19903    21920
74955    85610
65872     6763
93434     8391
95911    35041
96025    17519
Name: customer_zip_code_prefix, dtype: int64

In [19]:
customers['customer_zip_code_prefix'].min()

np.int64(1003)

In [20]:
customers['customer_zip_code_prefix'].max()

np.int64(99990)

In [21]:
customers[customers['customer_zip_code_prefix']<10000].shape[0]

23995

In [22]:
customers.to_csv("cleaned_customers.csv",index = False)

In [23]:
url1 = r"C:\Users\Karandeep Singh\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2\olist_orders_dataset.csv"

orders = pd.read_csv(url1)

In [24]:
orders.shape

(99441, 8)

In [25]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [26]:
orders.tail()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [27]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [28]:
orders_summary = pd.DataFrame({
    "Data Types" : orders.dtypes,
    "Null Values" : orders.isnull().sum(),
    "Duplicate Values" : orders.duplicated().sum()    
})

print(orders_summary)

                              Data Types  Null Values  Duplicate Values
order_id                             str            0                 0
customer_id                          str            0                 0
order_status                         str            0                 0
order_purchase_timestamp             str            0                 0
order_approved_at                    str          160                 0
order_delivered_carrier_date         str         1783                 0
order_delivered_customer_date        str         2965                 0
order_estimated_delivery_date        str            0                 0

In [29]:
orders[orders["order_approved_at"].isnull()].sort_values("order_approved_at").sample(20)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
19031,7013bcfc1c97fe719a7b5e05e61c12db,2941af76d38100e0f8740a374f1a5dc3,delivered,2017-02-18 13:29:47,NaN,2017-02-22 16:25:25,2017-03-01 08:07:38,2017-03-17 00:00:00
26800,c1d4211b3dae76144deccd6c74144a88,684cb238dc5b5d6366244e0e0776b450,delivered,2017-01-19 12:48:08,NaN,2017-01-25 14:56:50,2017-01-30 18:16:01,2017-03-01 00:00:00
3684,03310aa823a66056268a3bab36e827fb,25dbbf0c477fd4ae0880aaffbb12e8b3,canceled,2018-08-07 16:33:59,NaN,NaN,NaN,2018-09-04 00:00:00
63287,4b03319a5a065c83d4fcc4f18f8cb257,52215d2772a786a11c64720063c7ac4f,canceled,2017-10-20 12:42:26,NaN,NaN,NaN,2017-11-08 00:00:00
26618,02e723e8edb4a123d414f56cc9c4665e,6e9f7d9e943f9c0bdea278d9d7a1c9b9,canceled,2017-08-18 14:30:19,NaN,NaN,NaN,2017-09-21 00:00:00
52349,52ffca67c47f7bc4350f82b1d2c20dec,30b783882dd8572d3cf6a4ac7e605272,canceled,2017-11-26 18:42:08,NaN,NaN,NaN,2017-12-20 00:00:00
30150,92d731517f17c26f16182d45498c4c3d,95c44daefa7bfb91c6bb0665a0cd22fc,canceled,2016-10-05 11:23:13,NaN,NaN,NaN,2016-11-14 00:00:00
32691,1a5d21f44c73693b9930d0ca33a9d0b1,a21871375ed19fc3f2d8c62fdc75b9dc,canceled,2018-08-16 17:50:14,NaN,NaN,NaN,2018-09-12 00:00:00
5149,ea844c92cf978ea23321fa7fe5871761,6ddc45ad08e6a2c885ca2255fc52d6df,canceled,2018-09-13 09:56:12,NaN,NaN,NaN,2018-09-27 00:00:00
4373,4c8b9947280829d0a8b7e81cc249b875,403c35c4d8813bf67b3d396b91ca1619,canceled,2018-08-09 14:54:47,NaN,NaN,NaN,2018-08-21 00:00:00
1868,df8282afe61008dc26c6c31011474d02,aa797b187b5466bc6925aaaa4bb3bed1,canceled,2017-03-04 12:14:30,NaN,NaN,NaN,2017-04-10 00:00:00
30684,d177b7c08ed2934d5888e7fd236d42e1,045d8fcab59f603256eefe86e45f0350,canceled,2017-08-17 13:20:41,NaN,NaN,NaN,2017-09-04 00:00:00
61743,2eecb0d85f281280f79fa00f9cec1a95,a3d3c38e58b9d2dfb9207cab690b6310,delivered,2017-02-17 17:21:55,NaN,2017-02-22 11:42:51,2017-03-03 12:16:03,2017-03-20 00:00:00
1130,00b1cb0320190ca0daa2c88b35206009,3532ba38a3fd242259a514ac2b6ae6b6,canceled,2018-08-28 15:26:39,NaN,NaN,NaN,2018-09-12 00:00:00
31910,d2bc174d5c413f457a21db6899afb682,0337719c3caba8187a276942d35347fd,canceled,2018-08-09 09:50:42,NaN,NaN,NaN,2018-09-14 00:00:00
7457,9380c59012c11f49c549ef8dffef1367,07838708499d3eb9da748cb10b8ddf0a,canceled,2018-08-15 11:05:44,NaN,NaN,NaN,2018-09-21 00:00:00
93865,236e6ec6171c1870d4bcf4ccfad87f49,0fa12cb295663a40f53876e73aa7c460,canceled,2018-08-21 15:12:31,NaN,NaN,NaN,2018-09-11 00:00:00
83330,129ea9ae4b85283decb23ea1756f505d,8a0c8d55378e81be7bb18527a08dc0ef,canceled,2018-08-09 08:09:33,NaN,NaN,NaN,2018-09-25 00:00:00
70384,dbe2d1c6c34f5c31bb6736e1720c9b7e,3b5cb25012ce1400dbf62ed0995e1c14,canceled,2018-08-28 12:45:15,NaN,NaN,NaN,2018-09-03 00:00:00
91167,51192863a004d47d0e4f5bf5384bf88f,f2cc41062fa1cdfd6475afc3aaf9909f,canceled,2018-02-13 15:58:33,NaN,NaN,NaN,2018-03-07 00:00:00

In [30]:
orders[orders["order_delivered_carrier_date"].isnull()].sort_values("order_delivered_carrier_date").sample(20)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
82988,259fe605870f08ddf83ebb61f204b9e1,0a7dbfcfdf274bc1e1965b91489ba2f9,unavailable,2017-08-17 08:58:59,2017-08-19 02:16:08,NaN,NaN,2017-09-06 00:00:00
741,6a6c7d523fd59eb5bbefc007331af717,d954782ec6c0e911292c8a80757ef28d,processing,2017-11-24 20:09:33,2017-11-24 23:15:15,NaN,NaN,2017-12-20 00:00:00
94106,964bc1b427d6a485b515efcab9985e68,45ee903a8b62062d099b7c58fb4cc127,canceled,2018-02-25 21:11:16,2018-02-25 21:25:23,NaN,NaN,2018-03-19 00:00:00
73098,dc7a419b3cd13b51c38ff9442dfd4009,f97a6d5dc5996ca93920dba521495117,canceled,2017-03-21 19:17:48,2017-03-21 19:17:48,NaN,NaN,2017-04-17 00:00:00
45453,95fc4c1eda4eb09aff114067af28e084,474c28d22197efef5c36759ee917c242,processing,2017-03-05 21:02:51,2017-03-05 21:10:20,NaN,NaN,2017-03-23 00:00:00
26525,a9c8ac0c26c178f0ad33618f96225a01,727ab4449f530b9af13f40fa8e528bff,canceled,2018-07-22 23:36:14,2018-07-23 12:31:55,NaN,NaN,2018-08-07 00:00:00
44700,2e287cee637969033ec9ab49602e61ef,bf6418c67d6b29aada7d4a9a0cfb3e09,unavailable,2017-01-30 15:48:53,2017-01-31 04:31:22,NaN,NaN,2017-03-10 00:00:00
6312,f63be24880200ae32aa24f5b458a3dc3,a6954f48f5d8a0dcbad1a0921109cb56,unavailable,2017-01-27 13:39:53,2017-01-27 14:31:44,NaN,NaN,2017-03-16 00:00:00
61382,edb2a55c055efbb898171ec9fd840ab9,193fc54759c7948c87e0795ada003c69,invoiced,2016-10-06 16:34:16,2016-10-06 17:11:59,NaN,NaN,2016-11-28 00:00:00
55086,35de4050331c6c644cddc86f4f2d0d64,4ee64f4bfc542546f422da0aeb462853,created,2017-12-05 01:07:58,NaN,NaN,NaN,2018-01-08 00:00:00
10732,3e170726582244699b156f1c7044223a,6269066e0832481ece633f6d7d408a84,canceled,2017-11-06 15:47:20,2017-11-07 07:30:29,NaN,NaN,2017-11-28 00:00:00
30646,f7c983ea77108633138dd0ff5e2fbd3a,2625038eb968f0a5103f65539b3744f4,invoiced,2017-10-03 17:29:50,2017-10-04 02:43:39,NaN,NaN,2017-11-01 00:00:00
52961,bfb8512783ccd2271d2e96d3b856bf2b,4ee7fc32553f4f1cda85112b9a2719e3,invoiced,2017-09-16 12:37:51,2017-09-16 12:45:16,NaN,NaN,2017-10-06 00:00:00
45926,5808d10c07526976aa6125ada6f73fc0,fe7c7875de096a5aa735e7ae90ec580c,processing,2017-10-16 12:57:03,2017-10-18 03:09:20,NaN,NaN,2017-11-13 00:00:00
13595,d1f4276166cee5a37d01beb15e2426fc,4eadcffca4cbd545ee337b830acd0b6d,canceled,2018-02-26 06:37:45,2018-02-27 04:30:59,NaN,NaN,2018-03-12 00:00:00
74815,505d775eb158590af72d04189474e23c,45acf97b168ec16f75b8e504e62451a4,invoiced,2017-05-16 20:36:18,2017-05-16 20:50:13,NaN,NaN,2017-06-09 00:00:00
61634,6fff8d853d0647fc94776d0cfac0dc79,76ff8620a5c98e0bb71ebd0b2ab97af7,processing,2017-11-06 22:21:20,2017-11-07 07:30:43,NaN,NaN,2017-12-04 00:00:00
39998,33d8795f04dd631f3480d7aaf90da3dc,b11ea459107d514dd45bce81c0ab4e74,unavailable,2017-07-07 21:17:36,2017-07-07 21:30:13,NaN,NaN,2017-07-27 00:00:00
42097,54b56f2389dee113344da742da7890c9,fa75f83a777070af732410d2c43a9749,unavailable,2018-02-12 17:36:31,2018-02-12 17:47:59,NaN,NaN,2018-02-26 00:00:00
58173,0c2bc0e5935dcca29a9e0cc2e5236a13,b6615ef3680b677d2459723631d7cd3c,canceled,2017-11-09 12:11:56,2017-11-09 12:31:22,NaN,NaN,2017-12-01 00:00:00

In [31]:
orders['order_status'].nunique()

8

In [32]:
orders['order_status'].unique()

<StringArray>
[  'delivered',    'invoiced',     'shipped',  'processing', 'unavailable',
    'canceled',     'created',    'approved']
Length: 8, dtype: str

In [33]:
orders['order_status'].value_counts('order_status' == 'delivered')

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [34]:
orders[orders["order_delivered_customer_date"].isnull()].sort_values("order_delivered_customer_date").sample(20)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
25945,5f81f8debb479300dc3ae13616afb823,3a6e7307506713d97cd29c960e5f5a61,processing,2017-07-26 14:52:33,2017-07-27 10:15:17,NaN,NaN,2017-09-13 00:00:00
38603,b1591d0dddc34fc0db8601799e1fbd9f,887ff35acabd7ba225eab1330ac7154f,shipped,2017-08-01 20:26:19,2017-08-02 02:35:01,2017-08-02 20:52:08,NaN,2017-08-30 00:00:00
66555,04a2ba381317648726f46210a46ece95,4ae0a705c852353fbcdb27f8554b6655,canceled,2018-08-09 09:13:44,NaN,NaN,NaN,2018-09-06 00:00:00
10292,017c9c82265e832840e4209750680e94,1ff23faa252154298c3e52a1e36c1cda,shipped,2018-03-05 18:13:17,2018-03-05 19:00:26,2018-03-08 01:26:56,NaN,2018-03-26 00:00:00
90625,ec36a2bdf65bba1742263a91c4f251ae,6608dac8561577f1f1a18ff05e9d1dc7,canceled,2017-02-28 21:49:29,2017-02-28 22:01:44,NaN,NaN,2017-03-27 00:00:00
6897,28b219f462742fe93f57a52d18b67612,7ea93403888146228962dbe5e238a903,shipped,2017-09-28 12:19:33,2017-09-30 02:28:31,2017-10-04 22:46:27,NaN,2017-10-26 00:00:00
4189,0fb3b7bbfc3693b115aa62a83fad2714,9f546895f9d0841df86f8681992083b9,processing,2018-03-13 20:37:20,2018-03-13 21:40:22,NaN,NaN,2018-04-03 00:00:00
9915,dfee867c0e46410af48a712d2a4fa179,e06b5eac4efd083342ea205ec68fa5ba,processing,2017-05-20 19:09:21,2017-05-21 09:31:55,NaN,NaN,2017-06-13 00:00:00
33590,1c49e3fd28c9c369b12fd84446e475ab,14d2e011f94561a55aa3a97e0deff19e,processing,2017-04-06 07:04:06,2017-04-07 03:22:32,NaN,NaN,2017-04-27 00:00:00
24115,33fe1cb532ac16a48902980e00c26da6,e0669fc658288e9aea6d958ea90fb9b7,canceled,2017-07-25 19:26:15,NaN,NaN,NaN,2017-08-28 00:00:00
59808,b45e88e636c88f0aa9ba543bf538fa1d,236f7b080d8547793a424de49f9589a0,shipped,2017-05-12 13:06:00,2017-05-16 03:31:03,2017-05-17 11:07:37,NaN,2017-06-06 00:00:00
32382,d05cf40cb923ba228822414cc52067c3,2f8d1f27dbf2a944f1b5bda2de277ccf,canceled,2017-09-23 06:23:19,2017-09-23 07:00:06,NaN,NaN,2017-10-10 00:00:00
83622,57a82f32fdb1ce036662861d8dbb6a6b,58583807f8901eeed0810e81d58428fa,canceled,2017-11-20 21:36:39,2017-11-20 21:47:03,NaN,NaN,2017-12-01 00:00:00
32189,aa0639a3e2aa426f0b46f6a4c2d2efce,04872433c17e4ca13b0aa2381838d11e,shipped,2018-07-14 19:00:44,2018-07-14 19:15:15,2018-07-20 09:41:00,NaN,2018-08-07 00:00:00
20695,1a41f24ba682e06e82dd1ce5f77b6f5e,466417076987cafe57f66ad974bbab6b,unavailable,2017-07-09 13:28:08,2017-07-09 13:42:51,NaN,NaN,2017-07-21 00:00:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaN,NaN,2017-06-23 00:00:00
85009,80a4a10c7eb09d49ba31fc55d4efa53c,79718a1dd008d064a07683e902214896,shipped,2018-03-29 10:09:20,2018-03-29 10:27:49,2018-04-05 23:41:43,NaN,2018-04-17 00:00:00
98771,5a8a4dc28b16fb90469ad749f9535773,c0c8b8bb055100a0cc08dcc04d847ac9,canceled,2018-03-13 10:58:09,2018-03-14 03:08:35,NaN,NaN,2018-03-23 00:00:00
36018,28af73d7412f63a3e911be60bf966d70,368dbdc31e230a411c5d91546ab60ea3,shipped,2018-03-24 15:13:59,2018-03-24 15:27:44,2018-03-29 04:36:50,NaN,2018-04-20 00:00:00
81605,fa94c44f1539dcab4c8b936951d319d6,52267b6895bce2066b815bb3254e6a47,shipped,2018-07-08 20:02:19,2018-07-08 20:15:18,2018-07-17 15:48:00,NaN,2018-08-17 00:00:00

In [35]:
orders.groupby('order_status')[['order_approved_at', 
                                'order_delivered_carrier_date', 
                                'order_delivered_customer_date']].apply(lambda x: x.isnull().sum())

,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
order_status,,,
approved,0,2,2
canceled,141,550,619
created,5,5,5
delivered,14,2,8
invoiced,0,314,314
processing,0,301,301
shipped,0,0,1107
unavailable,0,609,609

In [36]:
order_deliver = orders[orders['order_status'] == 'delivered'][[
                                'order_approved_at', 
                                'order_delivered_carrier_date', 
                                'order_delivered_customer_date']]

rows_with_nulls = order_deliver[order_deliver.isnull().any(axis = 1)]

print(rows_with_nulls)

         order_approved_at order_delivered_carrier_date  \
3002   2017-11-28 17:56:40          2017-11-30 18:12:23
5323                   NaN          2017-02-23 12:04:47
16567                  NaN          2017-02-23 09:01:52
19031                  NaN          2017-02-22 16:25:25
20618  2018-06-20 07:19:05          2018-06-25 08:05:00
22663                  NaN          2017-02-22 11:23:10
23156                  NaN          2017-02-22 11:23:11
26800                  NaN          2017-01-25 14:56:50
38290                  NaN          2017-02-23 03:11:48
39334                  NaN          2017-02-23 07:23:36
43834  2018-07-01 17:15:12          2018-07-03 13:57:00
48401                  NaN          2017-01-27 11:08:05
61743                  NaN          2017-02-22 11:42:51
63052                  NaN          2017-02-23 03:09:14
67697                  NaN          2017-02-22 11:31:06
72407                  NaN          2017-02-22 11:31:30
73222  2017-09-29 09:07:16                          NaN
79263  2018-07-01 22:15:14          2018-07-03 13:57:00
82868  2018-07-01 21:29:54          2018-07-03 09:28:00
84999                  NaN          2017-02-22 11:23:11
92643  2017-05-25 23:30:16                          NaN
97647  2018-06-08 12:36:39          2018-06-12 14:10:00
98038  2018-06-27 16:29:30          2018-07-03 19:26:00

      order_delivered_customer_date
3002                            NaN
5323            2017-03-01 13:25:33
16567           2017-03-02 10:05:06
19031           2017-03-01 08:07:38
20618                           NaN
22663           2017-03-09 07:28:47
23156           2017-03-02 11:09:19
26800           2017-01-30 18:16:01
38290           2017-03-02 03:41:58
39334           2017-03-02 16:15:23
43834                           NaN
48401           2017-02-06 14:22:19
61743           2017-03-03 12:16:03
63052           2017-03-07 13:57:47
67697           2017-03-02 12:06:06
72407           2017-03-03 11:47:47
73222           2017-11-20 19:44:47
79263                           NaN
82868                           NaN
84999           2017-03-03 18:43:43
92643                           NaN
97647                           NaN
98038                           NaN

In [37]:
orders.to_csv("cleaned_orders.csv",index = False)

In [38]:
url2 = r"C:\Users\Karandeep Singh\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2\olist_order_items_dataset.csv"

order_items = pd.read_csv(url2)

In [39]:
order_items.shape

(112650, 7)

In [40]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [41]:
order_items.tail()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [42]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  str
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 6.0 MB

In [43]:
order_items_summary = pd.DataFrame({
    'Data Types' : order_items.dtypes,
    'Null Values' : order_items.isnull().sum(),
    'Duplicate Value' : order_items.duplicated().sum()
})

print(order_items_summary)

                    Data Types  Null Values  Duplicate Value
order_id                   str            0                0
order_item_id            int64            0                0
product_id                 str            0                0
seller_id                  str            0                0
shipping_limit_date        str            0                0
price                  float64            0                0
freight_value          float64            0                0

In [44]:
order_items['order_id'].nunique()

98666

In [45]:
order_items['order_id'].duplicated().sum()

np.int64(13984)

In [46]:
order_items.columns

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')

In [47]:
order_items_duplicate = order_items[[
    'order_id','order_item_id','product_id','seller_id',
    'shipping_limit_date','price','freight_value'
]]

# Count duplicates per column
duplicate_counts = pd.DataFrame({
    'Column': order_items_duplicate.columns,
    'DuplicateCount': [
        order_items_duplicate[col].duplicated().sum()
        for col in order_items_duplicate.columns
    ]
})

print(duplicate_counts)

                Column  DuplicateCount
0             order_id           13984
1        order_item_id          112629
2           product_id           79699
3            seller_id          109555
4  shipping_limit_date           19332
5                price          106682
6        freight_value          105651

In [48]:
order_items.duplicated(
    subset=["order_id", "order_item_id"]
).sum()

np.int64(0)

In [49]:
pd.to_datetime(order_items["shipping_limit_date"], errors="coerce").isnull().sum()

np.int64(0)

In [50]:
order_items["shipping_limit_date"] = pd.to_datetime(order_items["shipping_limit_date"])

In [51]:
order_items["shipping_limit_date"].dtype

dtype('<M8[us]')

In [52]:
(order_items["price"]<0).sum()

np.int64(0)

In [53]:
(order_items["price"] == 0).sum()

np.int64(0)

In [54]:
(order_items["freight_value"]<0).sum()

np.int64(0)

In [55]:
(order_items["freight_value"] == 0).sum()

np.int64(383)

In [56]:
order_items[order_items["freight_value"] == 0].head(20)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
114,00404fa7a687c8c44ca69d42695aae73,1,53b36df67ebb7c41585e8d54d6772e08,7d13fca15225358621be4086e1eb0964,2018-05-15 04:31:26,99.9,0.0
258,00a870c6c06346e85335524935c600c0,1,aca2eb7d00ea1a7b8ebd4e68314663af,955fee9216a65b617aa5c0531780ce60,2018-05-14 00:14:29,69.9,0.0
483,011c899816ea29773525bd3322dbb6aa,1,53b36df67ebb7c41585e8d54d6772e08,7d13fca15225358621be4086e1eb0964,2018-05-07 05:30:45,99.9,0.0
508,012b3f6ab7776a8ab3443a4ad7bef2e6,1,422879e10f46682990de24d770e7f83d,1f50f920176fa81dab994f9023523100,2018-05-09 21:30:50,53.9,0.0
509,012b3f6ab7776a8ab3443a4ad7bef2e6,2,422879e10f46682990de24d770e7f83d,1f50f920176fa81dab994f9023523100,2018-05-09 21:30:50,53.9,0.0
1784,04105b54650921ca3246f52e6f175f46,1,aca2eb7d00ea1a7b8ebd4e68314663af,955fee9216a65b617aa5c0531780ce60,2018-04-27 09:31:35,69.9,0.0
2232,0517a3e68dac3308995edca2144db36e,1,53b36df67ebb7c41585e8d54d6772e08,7d13fca15225358621be4086e1eb0964,2018-05-03 19:11:40,99.9,0.0
2714,061ba2e2d7544790b6ed6b5b4dd9278c,1,53b36df67ebb7c41585e8d54d6772e08,7d13fca15225358621be4086e1eb0964,2018-05-09 23:10:46,110.0,0.0
3224,07441f525824bc6b31d4dc19c5d49fc9,1,53b36df67ebb7c41585e8d54d6772e08,4869f7a5dfa277a7dca6462dcf3b52b2,2018-04-26 13:31:30,106.9,0.0
3378,079f16689c29acb6cab92978e6af2137,1,aca2eb7d00ea1a7b8ebd4e68314663af,955fee9216a65b617aa5c0531780ce60,2018-05-11 18:15:13,69.9,0.0
3648,0849ccbfff0e8fd7168be6a62ca74a0d,1,53b36df67ebb7c41585e8d54d6772e08,7d13fca15225358621be4086e1eb0964,2018-05-14 14:55:46,99.9,0.0
3878,08c3d8da1ee7ffc88a41cd145a4675ba,1,aca2eb7d00ea1a7b8ebd4e68314663af,955fee9216a65b617aa5c0531780ce60,2018-05-14 20:15:27,69.9,0.0
4464,0a0e91f265e0c09af322a473351b61d1,1,53b36df67ebb7c41585e8d54d6772e08,4869f7a5dfa277a7dca6462dcf3b52b2,2018-04-26 19:31:33,106.9,0.0
4465,0a0eb4fdd818ed6fb62d07792c948971,1,53b36df67ebb7c41585e8d54d6772e08,4869f7a5dfa277a7dca6462dcf3b52b2,2018-05-20 21:31:54,116.9,0.0
4510,0a2f51f07c7b99722f843490cd20ec09,1,aca2eb7d00ea1a7b8ebd4e68314663af,955fee9216a65b617aa5c0531780ce60,2018-05-28 00:18:27,69.9,0.0
4743,0ab73486735f114f9e844522fa9b16ec,1,53b36df67ebb7c41585e8d54d6772e08,7d13fca15225358621be4086e1eb0964,2018-05-04 10:12:30,99.9,0.0
4941,0b2d6210fb2a3be6f54add89639740ab,1,422879e10f46682990de24d770e7f83d,1f50f920176fa81dab994f9023523100,2018-04-27 11:31:20,53.9,0.0
5228,0bde6dfc382fc35f1a5ebf8ddf8e639d,1,53b36df67ebb7c41585e8d54d6772e08,7d13fca15225358621be4086e1eb0964,2018-05-03 21:52:29,99.9,0.0
5507,0c7207c23f4eb8c3b374c9b6f11d75b7,1,53b36df67ebb7c41585e8d54d6772e08,4869f7a5dfa277a7dca6462dcf3b52b2,2018-04-30 14:31:55,117.9,0.0
5608,0ca64e59f59b26fb6fb2726f907bb52d,1,53b36df67ebb7c41585e8d54d6772e08,7d13fca15225358621be4086e1eb0964,2018-05-09 16:30:41,99.9,0.0

In [57]:
order_items[["seller_id","product_id"]].nunique()

seller_id      3095
product_id    32951
dtype: int64

In [58]:
order_items[["seller_id","product_id"]].value_counts().sample(50)

seller_id                         product_id
05ff92fedb5be47920fea08e501238b9  555a2c02091cd2566c9d1852877018f9     1
f80edd2c5aaa505cc4b0a3b219abf4b8  452f66a0f164cac57802e2cea93188ac     2
e06f09ec0a4aca210779cf1cfc63cf19  926da363bc2ff4e30e0ee93403af0a44     1
ef506c96320abeedfb894c34db06f478  e4f77c9e32d6ed0e4902b08955d77b23     1
4a3ca9315b744ce9f8e9374361493884  b30bd2570ba0ad3ce06e785a7b23d544     4
87142160b41353c4e5fca2360caf6f92  70559c57b5e5cfac386368f45e744f55     1
fa1c13f2614d7b5c4749cbc52fecda94  8b5a201cdb79e1962baa08534f71d382     2
7b0df942f46435babab05d49b744b2c4  c3f538a01c95c92ddb8055bcfc6f4bd0     1
d379f449f2a3b271bc01c0782020f705  ca0439ecf23442fd24fcaf4c62b85ed5     2
5f1dc28029d2c244352a68107ec2b542  c7f00fc7c45096568acd0e79ade90e64     1
db4350fd57ae30082dec7acbaacc17f9  c8d90cfcce13c0471dc483876a080e87     2
abbf6046bbdf1028606a5bc7f00c99e7  6bbec39677851d73c72b2e8f256f34ad     1
a8739afb32aaa45e01815ca76f76f54b  7a49adf051c1e6fc5b639a98d17756f0     2
dbc22125167c298ef99da25668e1011f  6109d0cae3bcb57d579bc0fab6e61814    37
2e1c9f22be269ef4643f826c9e650a52  1de1b0e6f3e585714e7ba60c0fa2551c     1
af3ef48d0e13835e529c29ac573c63e5  d000acae704b825c2cbf14a022afaf05     1
96493fab2fbb13a14d0c0e8772eef5c3  e052d2aebe5b1887f31d80b47c2aa3c0     1
aced59e9b31ef866a94f9e7f29d8d418  b2775a101dfacb48184ed1c1cb4a278b     5
f9903dd0f812c7e771fcad47b6fff231  dbfc56759eb2cf348fed10084dd344f7     1
cd6efc47efaabf134f8bdb654e10b4f1  20e52965ed6d9e498b87dd87d050afbd     1
004c9cd9d87a3c30c522c48c4fc07416  7755707fe561ddbc56cefcce33c97945     1
968268a686aa05d1f529fb07dff08130  7329db39e452f3fa1b4f8285055a8e36     2
34056b8b55c1775a22af2331670a799c  8376fe38d749084ec4df862c696311d7     2
e333046ce6517bd8bb510291d44f0130  ceaaba49ab70be78825371ede54f32b4     1
daeb5653dd96c1b11860f72209795012  c3e4984fcd36ab7d67ec30a89f745113     1
da8622b14eb17ae2831f4ac5b9dab84a  fb783e3e545937820b57fe539b2c5a6c    21
d91fb3b7d041e83b64a00a3edfb37e4f  a000c3bbcabfea20a59fc2a10b9a6cf5     1
cc3d14116804f7209f3884f6367f1152  54f52360a2b571e7d7b54225b74bbccd     1
31ae0774c17fabd06ff707cc5bde005f  c4761af5e6a2183cc23c77a8d16f9d09     1
dc4a0fc896dc34b0d5bfec8438291c80  93c285dad77a797cf2193ead6afbe107     1
c37b2059d4f90d4feead554e5246565e  0bd5c2b2dd207f23739a694f006d63e6     5
620c87c171fb2a6dd6e8bb4dec959fc6  059ca09d32720d9adce3ae12e181339d     1
dd7ddc04e1b6c2c614352b383efe2d36  3dd3a67f72798f25cdd5d98553553d85     1
7d76b645482be4a332374e8223836592  a0f73bcb4e1fcfb056cfdc6ca7222249     2
e9bc59e7b60fc3063eb2290deda4cced  da662963d06871d0e88300f9c6df43ee     1
70a12e78e608ac31179aea7f8422044b  5eeb7a5563e8de6571e6ef18a65477c8     1
01fdefa7697d26ad920e9e0346d4bd1b  c033d17d5564326cf7986e7ffda1cf60     6
004c9cd9d87a3c30c522c48c4fc07416  880a54b4d8c28e6f7f519ae8caaa09db     1
8a432f4e5b471f8da497d7dc517666e2  d1b1a0e78589ee89279d0be1e4a8b905     6
4371b634e0efc0e22b09b52907d9d469  5d5a63339d6a39230bf2a276e8f8fe1c     1
efcd8d2104f1a05d028af7bad20d974b  0c46413e9062e5e91fdf39a9142427b5     1
579891617139df7d8671d373f0669622  fcd119ff3868ddbb0013932039418ede     1
0adac9fbd9a2b63cccaac4f8756c1ca8  ed08ea04c92f5f434c2362f7310fb328     5
f18112da765e0971ca5d510dec322bdd  c600d7f13104e8db2ca2b9fa78581409     1
76d5af76d0271110f9af36c92573f765  feb94d995efca232513a7baffff772b8     2
d91fb3b7d041e83b64a00a3edfb37e4f  05de46958121361ff78e2a9812db6778     2
b56906f7fd1696e043f1bcce164c487b  f08d78a6e7eecc6f3f51fad33ce7be1b     2
4830e40640734fc1c52cd21127c341d4  2043cae78c8b731c405c7329a05154b2    13
1c68394e931a64f90ea236c5ea590300  389c2351d11b4f543c93ceb7e966315d     1
6560211a19b47992c3666cc44a7e94c0  17ad136b7421ea8690fded631b651158    16
Name: count, dtype: int64

In [59]:
order_items.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  str
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  str
 3   seller_id            112650 non-null  str
 4   shipping_limit_date  112650 non-null  datetime64[us]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: datetime64[us](1), float64(2), int64(1), str(3)
memory usage: 6.0 MB

In [60]:
order_items.isnull().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [61]:
order_items.duplicated().sum()

np.int64(0)

In [62]:
order_items_duplicate = order_items[[
    'order_id','order_item_id','product_id','seller_id',
    'shipping_limit_date','price','freight_value'
]]

# Count duplicates per column
duplicate_counts = pd.DataFrame({
    'Column': order_items_duplicate.columns,
    'DuplicateCount': [
        order_items_duplicate[col].duplicated().sum()
        for col in order_items_duplicate.columns
    ]
})

print(duplicate_counts)

                Column  DuplicateCount
0             order_id           13984
1        order_item_id          112629
2           product_id           79699
3            seller_id          109555
4  shipping_limit_date           19332
5                price          106682
6        freight_value          105651

In [63]:
order_items.to_csv("cleaned_order_items.csv", index=False)

In [64]:
url3 = r"C:\Users\Karandeep Singh\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2\olist_products_dataset.csv"

products = pd.read_csv(url3)

In [65]:
products.shape

(32951, 9)

In [66]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  str
 1   product_category_name       32341 non-null  str
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), str(2)
memory usage: 2.3 MB

In [67]:
products.isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [68]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [69]:
products.tail()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [70]:
products.dtypes

product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [71]:
products_duplicate = products[[
    'product_id','product_category_name','product_name_lenght','product_description_lenght',
    'product_photos_qty','product_weight_g','product_length_cm','product_height_cm','product_width_cm'
]]

# Count duplicates per column
duplicate_counts = pd.DataFrame({
    'Column': products_duplicate.columns,
    'DuplicateCount': [
        products_duplicate[col].duplicated().sum()
        for col in products_duplicate.columns
    ]
})

print(duplicate_counts)

                       Column  DuplicateCount
0                  product_id               0
1       product_category_name           32877
2         product_name_lenght           32884
3  product_description_lenght           29990
4          product_photos_qty           32931
5            product_weight_g           30746
6           product_length_cm           32851
7           product_height_cm           32848
8            product_width_cm           32855

In [72]:
products.duplicated().sum()

np.int64(0)

In [73]:
products_summary = pd.DataFrame({
    'Data Types' : products.dtypes,
    'Null Values' : products.isnull().sum()
})

print(products_summary)

                           Data Types  Null Values
product_id                        str            0
product_category_name             str          610
product_name_lenght           float64          610
product_description_lenght    float64          610
product_photos_qty            float64          610
product_weight_g              float64            2
product_length_cm             float64            2
product_height_cm             float64            2
product_width_cm              float64            2

In [74]:
products[
    products["product_category_name"].isnull()
].shape

(610, 9)

In [75]:
products[
    products["product_category_name"].isnull()
].isnull().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                1
product_length_cm               1
product_height_cm               1
product_width_cm                1
dtype: int64

In [76]:
products["product_id"].duplicated().sum()

np.int64(0)

In [77]:
products['product_id'].nunique()

32951

In [78]:
products[products["product_category_name"].isnull()].sort_values("product_category_name").sample(20)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
19363,cebad0ed16ecd450b97d2be843d3da86,NaN,NaN,NaN,NaN,800.0,16.0,20.0,15.0
3612,b02a3f9824b29932f36a74d811f1b14c,NaN,NaN,NaN,NaN,2500.0,58.0,18.0,45.0
27679,2c24793fa7743021c907ec930fce14b9,NaN,NaN,NaN,NaN,1700.0,67.0,10.0,40.0
13898,34e01766eefd8ee844083f3d1f21653c,NaN,NaN,NaN,NaN,150.0,16.0,16.0,16.0
10713,f92119d44c137a84ea866dc12df68407,NaN,NaN,NaN,NaN,3100.0,30.0,40.0,30.0
2638,a08ffa6ecdd0ab3c1f4fe348acc2553b,NaN,NaN,NaN,NaN,1000.0,40.0,8.0,40.0
26060,3d4784f9a07ca5de370c86800589c860,NaN,NaN,NaN,NaN,1350.0,16.0,7.0,20.0
29929,abe135ae574a8969994de86975004972,NaN,NaN,NaN,NaN,900.0,26.0,18.0,18.0
27441,9032c8a4a91bb344eb53711d9fd71361,NaN,NaN,NaN,NaN,500.0,65.0,6.0,11.0
8062,beec9bc2305d3372fa3b3133ba3fd644,NaN,NaN,NaN,NaN,3000.0,40.0,40.0,40.0
18779,1d94d1e0c7fb2dcf2811e093d2ca303b,NaN,NaN,NaN,NaN,17150.0,62.0,36.0,46.0
23004,1bd0e965122ea1485d8f7f0c6792ebe0,NaN,NaN,NaN,NaN,500.0,25.0,6.0,16.0
12420,e2613182a3d5b61459d52f24823134fb,NaN,NaN,NaN,NaN,1900.0,20.0,6.0,11.0
15604,3f602d35212cda35342fc92d0ebc32e1,NaN,NaN,NaN,NaN,200.0,20.0,16.0,16.0
12378,b72e2daf4a916d46eb0076071027d05b,NaN,NaN,NaN,NaN,150.0,16.0,2.0,11.0
31476,ace8fb267a4f76c58dad79d0171f6812,NaN,NaN,NaN,NaN,26950.0,65.0,79.0,29.0
627,f0ea71b6e2ab4cb3bd8f5ba522a25a56,NaN,NaN,NaN,NaN,1300.0,30.0,20.0,30.0
1192,0fa699aaa0a38aa5d1de8e7fe04d2204,NaN,NaN,NaN,NaN,17900.0,48.0,32.0,28.0
3630,d64615580eb89e5d9a6ae0e37135a5fe,NaN,NaN,NaN,NaN,300.0,16.0,7.0,11.0
15092,7dc0fd89c290eb0b3e5253d19be59f6f,NaN,NaN,NaN,NaN,800.0,20.0,25.0,20.0

In [79]:
products[products["product_weight_g"].isnull()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [80]:
(products[["product_weight_g","product_length_cm","product_height_cm","product_width_cm"]] < 0).sum()

product_weight_g     0
product_length_cm    0
product_height_cm    0
product_width_cm     0
dtype: int64

In [81]:
(products["product_photos_qty"] < 0).sum()

np.int64(0)

In [82]:
(products["product_photos_qty"] == 0).sum()

np.int64(0)

In [83]:
products.isna().sum()

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [84]:
products.to_csv("cleaned_products.csv",index = False)

In [85]:
url4 = r"C:\Users\Karandeep Singh\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2\olist_order_payments_dataset.csv"

payments = pd.read_csv(url4)

In [86]:
payments.info()

<class 'pandas.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  str
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  str
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), str(2)
memory usage: 4.0 MB

In [87]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [88]:
payments.tail()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [89]:
payments_summary = pd.DataFrame({
    "Data Types" : payments.dtypes,
    "Null Values" : payments.isna().sum()
})

print(payments_summary)

                     Data Types  Null Values
order_id                    str            0
payment_sequential        int64            0
payment_type                str            0
payment_installments      int64            0
payment_value           float64            0

In [90]:
payments_duplicate = payments[[
    'order_id','payment_sequential','payment_type','payment_installments',
    'payment_value'
]]

# Count duplicates per column
duplicate_counts = pd.DataFrame({
    'Column': payments_duplicate.columns,
    'DuplicateCount': [
        payments_duplicate[col].duplicated().sum()
        for col in payments_duplicate.columns
    ]
})

print(duplicate_counts)

                 Column  DuplicateCount
0              order_id            4446
1    payment_sequential          103857
2          payment_type          103881
3  payment_installments          103862
4         payment_value           74809

In [91]:
payments.duplicated().sum()

np.int64(0)

In [92]:
payments.duplicated(
    subset=["order_id", "payment_sequential"]
).sum()

np.int64(0)

In [93]:
payments["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [94]:
payments.shape

(103886, 5)

In [95]:
payments[payments["payment_type"] == "not_defined"]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
51280,4637ca194b6387e2d538dc89b124b0ee,1,not_defined,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,not_defined,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,not_defined,1,0.0

In [96]:
payments[
    payments["payment_type"] == "not_defined"
][[
    "order_id",
    "payment_sequential",
    "payment_installments",
    "payment_value"
]]

,order_id,payment_sequential,payment_installments,payment_value
51280,4637ca194b6387e2d538dc89b124b0ee,1,1,0.0
57411,00b1cb0320190ca0daa2c88b35206009,1,1,0.0
94427,c8c528189310eaa44a745b8d9d26908b,1,1,0.0

In [97]:
orders[
    orders["order_id"].isin(
        payments.loc[
            payments["payment_type"] == "not_defined",
            "order_id"
        ]
    )
][[
    "order_id",
    "order_status",
    "order_purchase_timestamp",
    "order_approved_at"
]]

,order_id,order_status,order_purchase_timestamp,order_approved_at
1130,00b1cb0320190ca0daa2c88b35206009,canceled,2018-08-28 15:26:39,NaN
39919,4637ca194b6387e2d538dc89b124b0ee,canceled,2018-09-03 14:14:25,NaN
40235,c8c528189310eaa44a745b8d9d26908b,canceled,2018-08-28 20:05:14,NaN

In [98]:
(payments["payment_installments"] < 0).sum()

np.int64(0)

In [99]:
payments[payments["payment_installments"] == 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [100]:
payments[payments["payment_installments"] == 0].merge(
    orders[["order_id", "order_status"]],
    on="order_id",
    how="left"
)

,order_id,payment_sequential,payment_type,payment_installments,payment_value,order_status
0,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69,delivered
1,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94,delivered

In [101]:
payments[
    payments["order_id"].isin(
        payments.loc[
            payments["payment_installments"] == 0, "order_id"
        ]
    )
].sort_values("order_id")

,order_id,payment_sequential,payment_type,payment_installments,payment_value
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69

In [102]:
payments[
    payments["order_id"].isin(
        payments.loc[
            payments["payment_installments"] == 0,
            "order_id"
        ]
    )
].sort_values("order_id")

,order_id,payment_sequential,payment_type,payment_installments,payment_value
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69

In [103]:
payments[
    (payments["payment_type"] == "credit_card") &
    (payments["payment_value"] > 0) &
    (payments["payment_installments"] == 0)
]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [104]:
payments["payment_value"].min()

np.float64(0.0)

In [105]:
payments.to_csv("cleaned_order_payments.csv", index=False)

In [106]:
url5 = r"C:\Users\Karandeep Singh\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2\olist_order_reviews_dataset.csv"

order_reviews = pd.read_csv(url5)

In [107]:
order_reviews.shape

(99224, 7)

In [108]:
order_reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 5.3 MB

In [109]:
reviews_summary = pd.DataFrame({
    'Data types' : order_reviews.dtypes,
    'Null Values' : order_reviews.isna().sum()
})

print(reviews_summary)

                        Data types  Null Values
review_id                      str            0
order_id                       str            0
review_score                 int64            0
review_comment_title           str        87656
review_comment_message         str        58247
review_creation_date           str            0
review_answer_timestamp        str            0

In [110]:
order_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [111]:
order_reviews.tail()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
99219,574ed12dd733e5fa530cfd4bbf39d7c9,2a8c23fee101d4d5662fa670396eb8da,5,NaN,NaN,2018-07-07 00:00:00,2018-07-14 17:18:30
99220,f3897127253a9592a73be9bdfdf4ed7a,22ec9f0669f784db00fa86d035cf8602,5,NaN,NaN,2017-12-09 00:00:00,2017-12-11 20:06:42
99221,b3de70c89b1510c4cd3d0649fd302472,55d4004744368f5571d1f590031933e4,5,NaN,"Excelente mochila, entrega super rápida. Super...",2018-03-22 00:00:00,2018-03-23 09:10:43
99222,1adeb9d84d72fe4e337617733eb85149,7725825d039fc1f0ceb7635e3f7d9206,4,NaN,NaN,2018-07-01 00:00:00,2018-07-02 12:59:13
99223,efe49f1d6f951dd88b51e6ccd4cc548f,90531360ecb1eec2a1fbb265a0db0508,1,NaN,"meu produto chegou e ja tenho que devolver, po...",2017-07-03 00:00:00,2017-07-03 21:01:49

In [112]:
order_reviews.isna().mean() * 100

review_id                   0.000000
order_id                    0.000000
review_score                0.000000
review_comment_title       88.341530
review_comment_message     58.702532
review_creation_date        0.000000
review_answer_timestamp     0.000000
dtype: float64

In [113]:
order_reviews[['review_id','order_id']].duplicated().sum()

np.int64(0)

In [114]:
review_duplicate = order_reviews[[
    'review_id','order_id','review_score','review_comment_title',
    'review_comment_message','review_creation_date','review_answer_timestamp'
]]

# Count duplicates per column
duplicate_counts = pd.DataFrame({
    'Column': review_duplicate.columns,
    'DuplicateCount': [
        review_duplicate[col].duplicated().sum()
        for col in review_duplicate.columns
    ]
})

print(duplicate_counts)

                    Column  DuplicateCount
0                review_id             814
1                 order_id             551
2             review_score           99219
3     review_comment_title           94696
4   review_comment_message           63064
5     review_creation_date           98588
6  review_answer_timestamp             976

In [115]:
order_reviews['review_score'].value_counts().sort_index()

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [116]:
order_reviews[
    (order_reviews['review_score']<1) |
    (order_reviews['review_score']>5)
]

Empty DataFrame
Columns: [review_id, order_id, review_score, review_comment_title, review_comment_message, review_creation_date, review_answer_timestamp]
Index: []

In [117]:
order_reviews[
    order_reviews["review_comment_message"].isna()
]["review_score"].value_counts().sort_index()

review_score
1     2679
2     1006
3     4622
4    13166
5    36774
Name: count, dtype: int64

In [118]:
order_reviews['review_score'].unique()

array([4, 5, 1, 3, 2])

In [119]:
order_reviews[
    order_reviews["review_comment_title"].isna() &
    order_reviews["review_comment_message"].isna()
].shape

(56518, 7)

In [120]:
order_reviews["review_creation_date"] = pd.to_datetime(
    order_reviews["review_creation_date"],
    errors="coerce"
)

order_reviews["review_answer_timestamp"] = pd.to_datetime(
    order_reviews["review_answer_timestamp"],
    errors="coerce"
)

In [121]:
order_reviews[
    ["review_creation_date", "review_answer_timestamp"]
].isna().sum()

review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [122]:
order_reviews[[
    "review_creation_date",
    "review_answer_timestamp"
]].dtypes

review_creation_date       datetime64[us]
review_answer_timestamp    datetime64[us]
dtype: object

In [123]:
order_reviews[
    order_reviews["review_answer_timestamp"] < order_reviews["review_creation_date"]
].shape

(0, 7)

In [124]:
order_reviews[
    ["review_creation_date", "review_answer_timestamp"]
].agg(["min", "max"])

    review_creation_date review_answer_timestamp
min           2016-10-02     2016-10-07 18:32:28
max           2018-08-31     2018-10-29 12:27:35

In [125]:
reviews_summary_final = pd.DataFrame({
    "Data types": order_reviews.dtypes,
    "Null Values": order_reviews.isna().sum()
})

print(reviews_summary_final)

                             Data types  Null Values
review_id                           str            0
order_id                            str            0
review_score                      int64            0
review_comment_title                str        87656
review_comment_message              str        58247
review_creation_date     datetime64[us]            0
review_answer_timestamp  datetime64[us]            0

In [126]:
order_reviews.to_csv("cleaned_order_reviews.csv", index=False)

In [127]:
url6 = r"C:\Users\Karandeep Singh\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2\olist_sellers_dataset.csv"

sellers = pd.read_csv(url6)

In [128]:
sellers.shape

(3095, 4)

In [129]:
sellers.info()

<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

In [130]:
sellers_summary = pd.DataFrame({
    'Data Types' : sellers.dtypes,
    'Null Values' : sellers.isna().sum()
})

print(sellers_summary)

                       Data Types  Null Values
seller_id                     str            0
seller_zip_code_prefix      int64            0
seller_city                   str            0
seller_state                  str            0

In [131]:
sellers["seller_id"].duplicated().sum()

np.int64(0)

In [132]:
sellers["seller_state"].value_counts().sort_index()

seller_state
AC       1
AM       1
BA      19
CE      13
DF      30
ES      23
GO      40
MA       1
MG     244
MS       5
MT       4
PA       1
PB       6
PE       9
PI       1
PR     349
RJ     171
RN       5
RO       2
RS     129
SC     190
SE       2
SP    1849
Name: count, dtype: int64

In [133]:
sellers["seller_state"].nunique()

23

In [134]:
sellers["seller_city"].nunique()

611

In [135]:
sellers["seller_city"].sample(20, random_state=42)

1947    venancio aires
1309         rio claro
1606    belo horizonte
2626         sao paulo
2440          brasilia
1957           colombo
2723        mogi guacu
184              timbo
1260        vila velha
194     belo horizonte
2883         rio verde
2037         sao paulo
1941         sao paulo
314       porto alegre
102           ibitinga
1057     joao pinheiro
2788         sao paulo
2737    rio de janeiro
1779          criciuma
705       porto alegre
Name: seller_city, dtype: str

In [136]:
sellers["seller_city"].str.strip().ne(sellers["seller_city"]).sum()

np.int64(0)

In [137]:
(sellers["seller_zip_code_prefix"] < 10000).sum()

np.int64(1027)

In [138]:
(sellers["seller_zip_code_prefix"] < 1000).sum()

np.int64(0)

In [139]:
sellers["seller_zip_code_prefix"].astype(str).str.len().value_counts().sort_index()

seller_zip_code_prefix
4    1027
5    2068
Name: count, dtype: int64

In [140]:
sellers["seller_zip_code_prefix"] = (
    sellers["seller_zip_code_prefix"]
    .astype(str)
    .str.zfill(5)
)

In [141]:
sellers.dtypes

seller_id                 str
seller_zip_code_prefix    str
seller_city               str
seller_state              str
dtype: object

In [142]:
sellers["seller_zip_code_prefix"].str.len().value_counts()

seller_zip_code_prefix
5    3095
Name: count, dtype: int64

In [143]:
sellers["seller_zip_code_prefix"].dtype

In [144]:
sellers.to_csv("cleaned_sellers.csv", index=False)

In [145]:
url7 = r"C:\Users\Karandeep Singh\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2\product_category_name_translation.csv"

categorys = pd.read_csv(url7)

In [146]:
categorys.shape

(71, 2)

In [147]:
categorys.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

In [148]:
categorys_summary = pd.DataFrame({
    'Data Type': categorys.dtypes,
    'Null Value': categorys.isna().sum()
})

print(categorys_summary)

                              Data Type  Null Value
product_category_name               str           0
product_category_name_english       str           0

In [149]:
categorys.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [150]:
categorys.tail()

            product_category_name product_category_name_english
66                         flores                       flowers
67             artes_e_artesanato         arts_and_craftmanship
68                fraldas_higiene           diapers_and_hygiene
69  fashion_roupa_infanto_juvenil     fashion_childrens_clothes
70             seguros_e_servicos         security_and_services

In [151]:
categorys["product_category_name"].duplicated().sum()

np.int64(0)

In [152]:
categorys["product_category_name_english"].duplicated().sum()

np.int64(0)

In [153]:
(categorys["product_category_name"].str.strip() == "").sum()

np.int64(0)

In [154]:
(categorys["product_category_name_english"].str.strip() == "").sum()

np.int64(0)

In [155]:
categorys.to_csv("cleaned_category_translation.csv", index=False)

In [156]:
url8 = r"C:\Users\Karandeep Singh\.cache\kagglehub\datasets\olistbr\brazilian-ecommerce\versions\2\olist_geolocation_dataset.csv"

geolocation = pd.read_csv(url8)

In [157]:
geolocation.shape

(1000163, 5)

In [158]:
geolocation_summary = pd.DataFrame({
    'Data Types': geolocation.dtypes,
    'Null Values': geolocation.isna().sum()
})

print(geolocation_summary)

                            Data Types  Null Values
geolocation_zip_code_prefix      int64            0
geolocation_lat                float64            0
geolocation_lng                float64            0
geolocation_city                   str            0
geolocation_state                  str            0

In [159]:
(geolocation["geolocation_zip_code_prefix"] < 10000).sum()

np.int64(245733)

In [160]:
(geolocation["geolocation_zip_code_prefix"] < 1000).sum()

np.int64(0)

In [161]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [162]:
geolocation["geolocation_zip_code_prefix"].astype(str).str.len().value_counts().sort_index()

geolocation_zip_code_prefix
4    245733
5    754430
Name: count, dtype: int64

In [163]:
geolocation["geolocation_zip_code_prefix"] = (
    geolocation["geolocation_zip_code_prefix"]
    .astype(str)
    .str.zfill(5)
)

In [164]:
geolocation.dtypes

geolocation_zip_code_prefix        str
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

In [165]:
geolocation["geolocation_zip_code_prefix"].str.len().value_counts()

geolocation_zip_code_prefix
5    1000163
Name: count, dtype: int64

In [166]:
geolocation[["geolocation_lat", "geolocation_lng"]].describe()

       geolocation_lat  geolocation_lng
count     1.000163e+06     1.000163e+06
mean     -2.117615e+01    -4.639054e+01
std       5.715866e+00     4.269748e+00
min      -3.660537e+01    -1.014668e+02
25%      -2.360355e+01    -4.857317e+01
50%      -2.291938e+01    -4.663788e+01
75%      -1.997962e+01    -4.376771e+01
max       4.506593e+01     1.211054e+02

In [167]:
(
    (geolocation["geolocation_lat"] < -35) |
    (geolocation["geolocation_lat"] > 6) |
    (geolocation["geolocation_lng"] < -75) |
    (geolocation["geolocation_lng"] > -33)
).sum()

np.int64(40)

In [168]:
lat_problem = (
    (geolocation["geolocation_lat"] < -35) |
    (geolocation["geolocation_lat"] > 6)
).sum()

lng_problem = (
    (geolocation["geolocation_lng"] < -75) |
    (geolocation["geolocation_lng"] > -33)
).sum()

print("Latitude problems:", lat_problem)
print("Longitude problems:", lng_problem)

Latitude problems: 29
Longitude problems: 37

In [169]:
suspicious = (
    (geolocation["geolocation_lat"] < -35) |
    (geolocation["geolocation_lat"] > 6) |
    (geolocation["geolocation_lng"] < -75) |
    (geolocation["geolocation_lng"] > -33)
)

geolocation.loc[suspicious, "geolocation_state"].value_counts()

geolocation_state
PE    11
PA     7
RJ     4
RS     4
BA     3
PR     3
ES     2
MG     2
SP     1
AL     1
PB     1
MT     1
Name: count, dtype: int64

In [170]:
suspicious = (
    (geolocation["geolocation_lat"] < -35) |
    (geolocation["geolocation_lat"] > 6) |
    (geolocation["geolocation_lng"] < -75) |
    (geolocation["geolocation_lng"] > -33)
)

geolocation.loc[suspicious, "geolocation_state"].unique()

<StringArray>
['SP', 'RJ', 'ES', 'MG', 'BA', 'PE', 'AL', 'PB', 'PA', 'MT', 'PR', 'RS']
Length: 12, dtype: str

In [171]:
geolocation.loc[suspicious, "geolocation_zip_code_prefix"].value_counts().head(10)

geolocation_zip_code_prefix
53990    11
68275     5
98780     3
29654     2
35179     2
83252     2
18243     1
28165     1
28155     1
28333     1
Name: count, dtype: int64

In [172]:
zip_check = (
    geolocation.groupby("geolocation_zip_code_prefix")
    .agg(
        total_records=("geolocation_zip_code_prefix", "size"),
        unique_lat=("geolocation_lat", "nunique"),
        unique_lng=("geolocation_lng", "nunique")
    )
)

zip_check.loc[
    zip_check.index.isin(
        geolocation.loc[suspicious, "geolocation_zip_code_prefix"]
    )
]

                             total_records  unique_lat  unique_lng
geolocation_zip_code_prefix
18243                                    1           1           1
28155                                    5           5           5
28165                                    4           4           4
28333                                    7           6           6
28595                                   10           9           9
29654                                    4           4           4
35179                                   85          66          66
45936                                   35          32          32
46560                                    2           2           2
47310                                    5           5           5
53990                                   11           6           6
57319                                    3           2           2
58441                                    4           4           4
68275                                    9           6           6
68379                                    2           2           2
68447                                    5           5           5
78131                                    1           1           1
83252                                    2           1           1
83810                                    6           6           6
95130                                    1           1           1
98780                                  139         120         117

In [173]:
zip_status = (
    geolocation.assign(is_suspicious=suspicious)
    .groupby("geolocation_zip_code_prefix")["is_suspicious"]
    .value_counts()
    .unstack(fill_value=0)
    .rename(columns={False: "normal", True: "suspicious"})
)

zip_status.loc[
    zip_status.index.isin(
        geolocation.loc[suspicious, "geolocation_zip_code_prefix"]
    )
]

is_suspicious                normal  suspicious
geolocation_zip_code_prefix
18243                             0           1
28155                             4           1
28165                             3           1
28333                             6           1
28595                             9           1
29654                             2           2
35179                            83           2
45936                            34           1
46560                             1           1
47310                             4           1
53990                             0          11
57319                             2           1
58441                             3           1
68275                             4           5
68379                             1           1
68447                             4           1
78131                             0           1
83252                             0           2
83810                             5           1
95130                             0           1
98780                           136           3

In [174]:
geolocation["geolocation_zip_code_prefix"] = (
    geolocation["geolocation_zip_code_prefix"]
    .astype(str)
    .str.zfill(5)
)

In [175]:
geolocation["geolocation_zip_code_prefix"].str.len().value_counts()

geolocation_zip_code_prefix
5    1000163
Name: count, dtype: int64

In [176]:
print("City spaces:", geolocation["geolocation_city"].str.strip().ne(
    geolocation["geolocation_city"]
).sum())

print("State spaces:", geolocation["geolocation_state"].str.strip().ne(
    geolocation["geolocation_state"]
).sum())

print("Unique states:", geolocation["geolocation_state"].nunique())

City spaces: 1
State spaces: 0
Unique states: 27

In [177]:
geolocation["geolocation_city"] = (
    geolocation["geolocation_city"].str.strip()
)

In [178]:
geolocation["geolocation_city"].str.strip().ne(
    geolocation["geolocation_city"]
).sum()

np.int64(0)

In [179]:
geolocation.to_csv("cleaned_geolocation.csv", index=False)

In [180]:
import pandas as pd

customers = pd.read_csv("cleaned_customers.csv")
orders = pd.read_csv("cleaned_orders.csv")
order_items = pd.read_csv("cleaned_order_items.csv")
products = pd.read_csv("cleaned_products.csv")
payments = pd.read_csv("cleaned_order_payments.csv")
reviews = pd.read_csv("cleaned_order_reviews.csv")
sellers = pd.read_csv("cleaned_sellers.csv")
category_translation = pd.read_csv("cleaned_category_translation.csv")
geolocation = pd.read_csv("cleaned_geolocation.csv")

In [181]:
print("Customers:", customers.shape)
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)
print("Products:", products.shape)
print("Payments:", payments.shape)
print("Reviews:", reviews.shape)
print("Sellers:", sellers.shape)
print("Category Translation:", category_translation.shape)
print("Geolocation:", geolocation.shape)

Customers: (99441, 5)
Orders: (99441, 8)
Order Items: (112650, 7)
Products: (32951, 9)
Payments: (103886, 5)
Reviews: (99224, 7)
Sellers: (3095, 4)
Category Translation: (71, 2)
Geolocation: (1000163, 5)

In [182]:
orders["order_id"].nunique()

99441

In [183]:
order_items["order_id"].nunique()

98666

In [184]:
order_items["order_id"].duplicated().sum()

np.int64(13984)

In [185]:
orders_without_items = orders[
    ~orders["order_id"].isin(order_items["order_id"])
]

print("Orders without items:", orders_without_items.shape[0])

Orders without items: 775

In [186]:
orders_without_items["order_status"].value_counts()

order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64

In [187]:
order_items[
    ~order_items["order_id"].isin(orders["order_id"])
].shape

(0, 7)

In [188]:
set(order_items.columns) & set(orders.columns)

{'order_id'}

In [189]:
orders["order_id"].duplicated().sum()

np.int64(0)

In [190]:
master_df = order_items.merge(
    orders,
    on="order_id",
    how="left"
)

In [191]:
print("Before merge:", order_items.shape)
print("After merge:", master_df.shape)

Before merge: (112650, 7)
After merge: (112650, 14)

In [192]:
master_df["product_id"].nunique()

32951

In [193]:
master_df[
    ~master_df["product_id"].isin(products["product_id"])
].shape

(0, 14)

In [194]:
products["product_id"].duplicated().sum()

np.int64(0)

In [195]:
master_df = master_df.merge(
    products,
    on="product_id",
    how="left",
    validate="many_to_one"
)

In [196]:
print(master_df.shape)

(112650, 22)

In [197]:
master_df["seller_id"].nunique()

3095

In [198]:
master_df[
    ~master_df["seller_id"].isin(sellers["seller_id"])
].shape

(0, 22)

In [199]:
sellers["seller_id"].duplicated().sum()

np.int64(0)

In [200]:
master_df = master_df.merge(
    sellers,
    on="seller_id",
    how="left",
    validate="many_to_one"
)

In [201]:
print(master_df.shape)

(112650, 25)

In [202]:
payments.groupby("order_id").size().value_counts().sort_index()

1     96479
2      2382
3       301
4       108
5        52
6        36
7        28
8        11
9         9
10        5
11        8
12        8
13        3
14        2
15        2
19        2
21        1
22        1
26        1
29        1
Name: count, dtype: int64

In [203]:
payment_summary = (
    payments.groupby("order_id")
    .agg(
        payment_count=("payment_sequential", "count"),
        payment_value_total=("payment_value", "sum"),
        payment_installments_max=("payment_installments", "max"),
        payment_types=("payment_type", lambda x: ", ".join(sorted(x.unique())))
    )
    .reset_index()
)

In [204]:
print(payment_summary.shape)
print(payment_summary["order_id"].duplicated().sum())

(99440, 5)
0

In [205]:
master_df = master_df.merge(
    payment_summary,
    on="order_id",
    how="left",
    validate="many_to_one"
)

In [206]:
print(master_df.shape)

(112650, 29)

In [207]:
reviews.groupby("order_id").size().value_counts().sort_index()

1    98126
2      543
3        4
Name: count, dtype: int64

In [208]:
reviews["order_id"].duplicated().sum()

np.int64(551)

In [209]:
reviews["order_id"].nunique()

98673

In [210]:
review_summary = (
    reviews.groupby("order_id")
    .agg(
        review_count=("review_score", "count"),
        review_score_avg=("review_score", "mean"),
        review_score_min=("review_score", "min"),
        review_score_max=("review_score", "max")
    )
    .reset_index()
)

In [211]:
print(review_summary.shape)
print(review_summary["order_id"].duplicated().sum())

(98673, 5)
0

In [212]:
master_df = master_df.merge(
    review_summary,
    on="order_id",
    how="left",
    validate="many_to_one"
)

In [216]:
print(master_df.shape)

(112650, 33)

In [214]:
category_translation["product_category_name"].duplicated().sum()

np.int64(0)

In [215]:
master_df[
    ~master_df["product_category_name"].isin(
        category_translation["product_category_name"]
    )
].shape

(1627, 33)

In [217]:
print("Master before review merge:", master_df.shape)
print("Review summary:", review_summary.shape)

Master before review merge: (112650, 33)
Review summary: (98673, 5)

In [218]:
master_df["order_id"].nunique()
review_summary["order_id"].nunique()

98673

In [219]:
master_df["product_category_name"].isna().sum()

np.int64(1603)

In [220]:
master_df[
    master_df["product_category_name"].isna()
].shape

(1603, 33)

In [221]:
master_df = master_df.merge(
    category_translation,
    on="product_category_name",
    how="left",
    validate="many_to_one"
)

In [222]:
print(master_df.shape)

(112650, 34)

In [223]:
master_df[["order_id", "order_item_id"]].duplicated().sum()

np.int64(0)

In [224]:
master_df.isna().sum()

order_id                            0
order_item_id                       0
product_id                          0
seller_id                           0
shipping_limit_date                 0
price                               0
freight_value                       0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                  15
order_delivered_carrier_date     1194
order_delivered_customer_date    2454
order_estimated_delivery_date       0
product_category_name            1603
product_name_lenght              1603
product_description_lenght       1603
product_photos_qty               1603
product_weight_g                   18
product_length_cm                  18
product_height_cm                  18
product_width_cm                   18
seller_zip_code_prefix              0
seller_city                         0
seller_state                        0
payment_count                       3
payment_value_total                 3
payment_installments_max            3
payment_types                       3
review_count                      942
review_score_avg                  942
review_score_min                  942
review_score_max                  942
product_category_name_english    1627
dtype: int64

In [225]:
missing_english = master_df[
    master_df["product_category_name"].notna() &
    master_df["product_category_name_english"].isna()
]

missing_english.shape

(24, 34)

In [226]:
missing_english["product_category_name"].value_counts()

product_category_name
portateis_cozinha_e_preparadores_de_alimentos    15
pc_gamer                                          9
Name: count, dtype: int64

In [227]:
print("Rows:", master_df.shape[0])
print("Columns:", master_df.shape[1])
print("Duplicate rows:", master_df.duplicated().sum())

Rows: 112650
Columns: 34
Duplicate rows: 0

In [228]:
master_df.dtypes

order_id                             str
order_item_id                      int64
product_id                           str
seller_id                            str
shipping_limit_date                  str
price                            float64
freight_value                    float64
customer_id                          str
order_status                         str
order_purchase_timestamp             str
order_approved_at                    str
order_delivered_carrier_date         str
order_delivered_customer_date        str
order_estimated_delivery_date        str
product_category_name                str
product_name_lenght              float64
product_description_lenght       float64
product_photos_qty               float64
product_weight_g                 float64
product_length_cm                float64
product_height_cm                float64
product_width_cm                 float64
seller_zip_code_prefix             int64
seller_city                          str
seller_state                         str
payment_count                    float64
payment_value_total              float64
payment_installments_max         float64
payment_types                        str
review_count                     float64
review_score_avg                 float64
review_score_min                 float64
review_score_max                 float64
product_category_name_english        str
dtype: object

In [229]:
date_columns = [
    "shipping_limit_date",
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

master_df[date_columns] = master_df[date_columns].apply(pd.to_datetime)

master_df[date_columns].dtypes

shipping_limit_date              datetime64[us]
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [230]:
master_df[date_columns].isna().sum()

shipping_limit_date                 0
order_purchase_timestamp            0
order_approved_at                  15
order_delivered_carrier_date     1194
order_delivered_customer_date    2454
order_estimated_delivery_date       0
dtype: int64

In [231]:
print("Shape:", master_df.shape)
print("Duplicate rows:", master_df.duplicated().sum())
print("Duplicate order-item keys:",
      master_df[["order_id", "order_item_id"]].duplicated().sum())
print("Missing order IDs:", master_df["order_id"].isna().sum())
print("Missing product IDs:", master_df["product_id"].isna().sum())
print("Missing seller IDs:", master_df["seller_id"].isna().sum())

Shape: (112650, 34)
Duplicate rows: 0
Duplicate order-item keys: 0
Missing order IDs: 0
Missing product IDs: 0
Missing seller IDs: 0

In [232]:
master_df.to_csv(
    "olist_master_dataset.csv",
    index=False
)

In [233]:
import os

print(os.path.exists("olist_master_dataset.csv"))

True